/**
 * 行知 Navi — 虚构 Demo 数据
 * 状态：flowing 顺利 | active 正在做 | blocked 卡住了 | waiting 在等前面的事 | done 已完成
 */
window.NAVI_DATA = {
  user: {
    name: "林予",
    title: "产品与研究",
  },
  generatedAt: "2026-09-15T17:40:00+08:00",
  nodes: [
    {
      id: "root",
      parentId: null,
      name: "我的状态",
      type: "root",
      domain: null,
    },

    /* ——— 工作 ——— */
    {
      id: "work",
      parentId: "root",
      name: "工作",
      type: "domain",
      domain: "work",
      brief: "这周主要是把 Q3 规划收个尾，再和别的组碰一下。",
    },
    {
      id: "work-q3",
      parentId: "work",
      name: "Q3 产品规划",
      type: "project",
      domain: "work",
      progress: 0.46,
      status: "blocked",
      brief: "路线图还写不下去，访谈的人没约齐。",
      blockedReason: "访谈还差两场，现在聊到的人来路太像，材料没法定下来。",
      deps: ["work-q3-interview"],
      estimateMin: 25,
      nextAction: "先把剩下两场访谈约上",
      nextHint: "给两位各发一封邮件，把周四和周五各占一个时段。这次不用准备提纲，人来就行。",
      updatedAt: "今天 16:20",
    },
    {
      id: "work-q3-compete",
      parentId: "work-q3",
      name: "竞品对照表",
      type: "task",
      domain: "work",
      progress: 1,
      status: "done",
      brief: "四家主要竞品的用法都过了一遍。",
      estimateMin: 0,
      nextAction: "暂时不用管",
      nextHint: "已经收好了，到时候直接当附件发出去。",
      updatedAt: "昨天 21:10",
    },
    {
      id: "work-q3-interview",
      parentId: "work-q3",
      name: "用户访谈记录",
      type: "task",
      domain: "work",
      progress: 0.4,
      status: "blocked",
      brief: "聊完了 3 个，还有 2 个这周放了两次鸽子。",
      blockedReason: "两位受访者一直往后推，这周只剩周四下午和周五早上有空。",
      deps: [],
      estimateMin: 25,
      nextAction: "发两封邮件，把剩下的时间定下来",
      nextHint: "模板在草稿箱里，改个时间就能发。发完记得把这张卡片改成「正在做」。",
      updatedAt: "今天 14:05",
    },
    {
      id: "work-q3-roadmap",
      parentId: "work-q3",
      name: "路线图草案",
      type: "task",
      domain: "work",
      progress: 0.15,
      status: "waiting",
      brief: "框架搭好了，但结论得等访谈。",
      blockedReason: "等「用户访谈记录」聊完。",
      deps: ["work-q3-interview"],
      estimateMin: 50,
      nextAction: "等访谈结束再动笔",
      nextHint: "现在别急着写。访谈谈完，花 50 分钟把三个主题收成一页结论。",
      updatedAt: "今天 11:30",
    },
    {
      id: "work-align",
      parentId: "work",
      name: "这周的沟通",
      type: "project",
      domain: "work",
      progress: 0.72,
      status: "active",
      brief: "晨会开完了，还有一件事得跟设计组当面确认一下。",
      deps: ["work-align-deps"],
      estimateMin: 15,
      nextAction: "问问设计组图标哪天能给",
      nextHint: "在群里问一句就行，回复顺手记在这儿。",
      updatedAt: "今天 10:12",
    },
    {
      id: "work-align-standup",
      parentId: "work-align",
      name: "周一晨会记录",
      type: "task",
      domain: "work",
      progress: 1,
      status: "done",
      brief: "有风险的地方已经跟组长说过了。",
      updatedAt: "周一 10:40",
    },
    {
      id: "work-align-deps",
      parentId: "work-align",
      name: "跟设计组确认时间",
      type: "task",
      domain: "work",
      progress: 0.5,
      status: "active",
      brief: "研发那边说好了，设计那边还没给日子。",
      estimateMin: 15,
      nextAction: "问清设计组图标哪天交付",
      nextHint: "问清楚是这周四之前，还是下周一。答复含糊就先标成风险。",
      updatedAt: "今天 10:12",
    },

    /* ——— 学习 ——— */
    {
      id: "study",
      parentId: "root",
      name: "学习",
      type: "domain",
      domain: "study",
      brief: "主要在啃系统设计，英语保持最低量就行。",
    },
    {
      id: "study-ddia",
      parentId: "study",
      name: "系统设计进阶",
      type: "project",
      domain: "study",
      progress: 0.38,
      status: "active",
      brief: "在读事务和隔离级别，笔记已经落下一章了。",
      estimateMin: 35,
      nextAction: "把第 7 章剩下的 12 页读完，写下三条结论",
      nextHint: "别做整本书的笔记。只写三条：脏读、不可重复读、幻读，各举一个自己碰过的例子。",
      updatedAt: "昨天 22:40",
    },
    {
      id: "study-ddia-ch7",
      parentId: "study-ddia",
      name: "第 7 章：事务",
      type: "task",
      domain: "study",
      progress: 0.55,
      status: "active",
      brief: "前半章划完了，隔离级别还没能用自己的话说一遍。",
      estimateMin: 35,
      nextAction: "读完剩下 12 页，写三个隔离级别的例子",
      nextHint: "手机开勿扰。读完马上写，别另开一个文档。",
      updatedAt: "昨天 22:40",
    },
    {
      id: "study-ddia-notes",
      parentId: "study-ddia",
      name: "章节笔记回写",
      type: "task",
      domain: "study",
      progress: 0.1,
      status: "waiting",
      brief: "等第 7 章读完一起整理。",
      deps: ["study-ddia-ch7"],
      estimateMin: 20,
      nextAction: "读完再整理",
      nextHint: "只留下周还用得上的定义，摘抄的部分删掉。",
      updatedAt: "昨天 22:40",
    },
    {
      id: "study-en",
      parentId: "study",
      name: "英语精读",
      type: "project",
      domain: "study",
      progress: 0.33,
      status: "active",
      brief: "这周想读 3 篇，已经读完 1 篇。",
      estimateMin: 20,
      nextAction: "把第二篇读完：《人月神话》节选",
      nextHint: "最多标 8 个生词。读完用两句话说说讲了什么。",
      updatedAt: "周日 20:15",
    },

    /* ——— 生活 ——— */
    {
      id: "life",
      parentId: "root",
      name: "生活",
      type: "domain",
      domain: "life",
      brief: "作息还算稳，运动差一次，回家的行程还没定。",
    },
    {
      id: "life-health",
      parentId: "life",
      name: "作息和运动",
      type: "project",
      domain: "life",
      progress: 0.74,
      status: "flowing",
      brief: "连着 5 天睡够了，运动做完 2 次，还差 1 次。",
      estimateMin: 40,
      nextAction: "今晚把第三次有氧补上（慢跑或跳绳都行）",
      nextHint: "下班先换衣服，别先开电脑。加上热身 40 分钟。",
      updatedAt: "今天 07:20",
    },
    {
      id: "life-sleep",
      parentId: "life-health",
      name: "睡眠记录",
      type: "task",
      domain: "life",
      progress: 0.86,
      status: "flowing",
      brief: "最近 7 天平均睡了 7.2 小时。",
      nextAction: "继续保持 23:30 前放下手机",
      nextHint: "不用额外做什么，保持就好。",
      updatedAt: "今天 07:20",
    },
    {
      id: "life-sport",
      parentId: "life-health",
      name: "本周运动 3 次",
      type: "task",
      domain: "life",
      progress: 0.67,
      status: "active",
      brief: "周二练了力量，周四跑了步。",
      estimateMin: 40,
      nextAction: "今晚或者明早，把第三次补上",
      nextHint: "今晚 19:30 出门最稳妥，别拖到周日，那天的行程会挤。",
      updatedAt: "周四 19:50",
    },
    {
      id: "life-home",
      parentId: "life",
      name: "周末回家",
      type: "project",
      domain: "life",
      progress: 0.2,
      status: "waiting",
      brief: "票和晚饭都还没定，得先问问家里什么时候方便。",
      blockedReason: "还没问过爸妈周六有没有别的安排。",
      deps: ["life-home-ask"],
      estimateMin: 10,
      nextAction: "给家里打个电话，问问周六几点吃晚饭",
      nextHint: "顺便问清几个人、几点到，再去买票。别先下单。",
      updatedAt: "昨天 19:00",
    },
    {
      id: "life-home-ask",
      parentId: "life-home",
      name: "问一下家里的时间",
      type: "task",
      domain: "life",
      progress: 0,
      status: "active",
      brief: "打个电话就解决了。",
      estimateMin: 10,
      nextAction: "今晚 8 点前打个电话",
      nextHint: "顺便问：几号回、谁在家、要不要带点东西。",
      updatedAt: "昨天 19:00",
    },

    /* ——— 项目 ——— */
    {
      id: "proj",
      parentId: "root",
      name: "项目",
      type: "domain",
      domain: "proj",
      brief: "知识库搬家卡在标签上，别的先放放。",
    },
    {
      id: "proj-kb",
      parentId: "proj",
      name: "个人知识库迁移",
      type: "project",
      domain: "proj",
      progress: 0.34,
      status: "blocked",
      brief: "旧笔记都导出来了，标签怎么分还没想好。",
      blockedReason: "一会儿想按主题分，一会儿想按来源分，脚本不敢跑。",
      deps: ["proj-kb-taxonomy"],
      estimateMin: 25,
      nextAction: "先定一套最少的标签",
      nextHint: "只留 8 个主题标签，再加 3 个状态就够。来源用文件夹区分，别塞进标签。",
      updatedAt: "今天 15:48",
    },
    {
      id: "proj-kb-export",
      parentId: "proj-kb",
      name: "旧笔记导出",
      type: "task",
      domain: "proj",
      progress: 1,
      status: "done",
      brief: "612 篇笔记，都备份好了。",
      updatedAt: "上周五 18:02",
    },
    {
      id: "proj-kb-taxonomy",
      parentId: "proj-kb",
      name: "标签怎么分",
      type: "task",
      domain: "proj",
      progress: 0.25,
      status: "blocked",
      brief: "草稿列了 26 个标签，太多了。",
      blockedReason: "标准定不下来，试标 20 篇就有一堆不知道该放哪。",
      estimateMin: 25,
      nextAction: "砍到 8 个主题加 3 个状态，拿 10 篇试试",
      nextHint: "来源类的标签全删。拿不准的一律先放「未分类」。",
      updatedAt: "今天 15:48",
    },
    {
      id: "proj-kb-import",
      parentId: "proj-kb",
      name: "导入脚本",
      type: "task",
      domain: "proj",
      progress: 0,
      status: "waiting",
      brief: "脚本架子有了，就差最后的字段。",
      deps: ["proj-kb-taxonomy"],
      blockedReason: "等标签定下来。",
      estimateMin: 45,
      nextAction: "标签定了再跑导入",
      nextHint: "先拿 30 篇试一下，别一次全导。",
      updatedAt: "昨天 16:10",
    },
    {
      id: "proj-side",
      parentId: "proj",
      name: "侧项目：阅读俱乐部",
      type: "project",
      domain: "proj",
      progress: 1,
      status: "done",
      brief: "下一期的书和导读都发出去了。",
      nextAction: "暂时不用管",
      nextHint: "这周的事做完了，到日子参加就行。",
      updatedAt: "周日 21:00",
    },
  ],
};

window.NAVI_META = {
  domains: [
    { id: "work", name: "工作", kicker: "手上的活" },
    { id: "study", name: "学习", kicker: "在学的东西" },
    { id: "life", name: "生活", kicker: "日子和人" },
    { id: "proj", name: "项目", kicker: "慢慢做的事" },
  ],
  statusLabel: {
    flowing: "顺利",
    active: "正在做",
    blocked: "卡住了",
    waiting: "在等前面的事",
    done: "已完成",
  },
};

window.NAVI_EMPTY_NODES = function (name) {
  return [
    { id: "root", parentId: null, name: name + "的状态", type: "root", domain: null },
    { id: "work", parentId: "root", name: "工作", type: "domain", domain: "work", brief: "还没填什么。" },
    { id: "study", parentId: "root", name: "学习", type: "domain", domain: "study", brief: "还没填什么。" },
    { id: "life", parentId: "root", name: "生活", type: "domain", domain: "life", brief: "还没填什么。" },
    { id: "proj", parentId: "root", name: "项目", type: "domain", domain: "proj", brief: "还没填什么。" },
    {
      id: "work-start",
      parentId: "work",
      name: "这周最想做的一件事",
      type: "project",
      domain: "work",
      progress: 0,
      status: "active",
      brief: "刚建好，状态图还是空的。",
      estimateMin: 15,
      nextAction: "写下这周最想做完的一件事",
      nextHint: "一句话就行，不用拆成小任务。",
      updatedAt: "刚刚",
    },
  ];
};

window.NAVI_SEED_USERS = [
  {
    id: "u-lin",
    name: "林予",
    title: "产品与研究",
    note: "Q3 规划卡在访谈上，知识库搬家也停着。",
    tone: "rose",
  },
  {
    id: "u-chen",
    name: "陈拾",
    title: "后端工程",
    note: "快发布了，告警还没人认领。",
    tone: "sage",
  },
  {
    id: "u-an",
    name: "安然",
    title: "体验设计",
    note: "稿子交出去了，这周过得挺稳。",
    tone: "sand",
  },
  {
    id: "u-zhou",
    name: "周南",
    title: "在读研究生",
    note: "开题报告还在等老师回。",
    tone: "lilac",
  },
];

window.NAVI_PACKS = {
  "u-lin": { nodes: window.NAVI_DATA.nodes },
  "u-chen": {
    nodes: [
      { id: "root", parentId: null, name: "我的状态", type: "root" },
      { id: "work", parentId: "root", name: "工作", type: "domain", domain: "work", brief: "发布前，稳定是第一位的。" },
      {
        id: "work-rel",
        parentId: "work",
        name: "9 月发布",
        type: "project",
        domain: "work",
        progress: 0.7,
        status: "blocked",
        brief: "功能都合进去了，就是告警谁来管还没定。",
        blockedReason: "值班表和告警怎么转还没说好，流量不敢切。",
        deps: ["work-oncall"],
        estimateMin: 20,
        nextAction: "把告警转发的草稿发到值班群确认一下",
        nextHint: "只确认 P1 找谁，别动规则本身。",
        updatedAt: "今天 15:10",
      },
      {
        id: "work-oncall",
        parentId: "work-rel",
        name: "谁来管告警",
        type: "task",
        domain: "work",
        progress: 0.2,
        status: "blocked",
        brief: "名单上还缺两个人的联系方式。",
        blockedReason: "新同事的入职信息还没同步过来。",
        estimateMin: 20,
        nextAction: "跟组里要一下两位新同学的联系方式",
        nextHint: "私聊问就行，别发大群。",
        updatedAt: "今天 15:10",
      },
      { id: "study", parentId: "root", name: "学习", type: "domain", domain: "study", brief: "这周只保持读点东西。" },
      {
        id: "study-sre",
        parentId: "study",
        name: "SRE 笔记",
        type: "project",
        domain: "study",
        progress: 0.4,
        status: "active",
        estimateMin: 25,
        nextAction: "补一页「错误预算」的笔记",
        nextHint: "就着这次发布写，别另开一个题目。",
        updatedAt: "昨天",
      },
      { id: "life", parentId: "root", name: "生活", type: "domain", domain: "life", brief: "睡得还行。" },
      {
        id: "life-rest",
        parentId: "life",
        name: "作息",
        type: "project",
        domain: "life",
        progress: 0.6,
        status: "flowing",
        nextAction: "保持 12 点前睡",
        nextHint: "发布这周，破例一次也没关系。",
        updatedAt: "今天",
      },
      { id: "proj", parentId: "root", name: "项目", type: "domain", domain: "proj", brief: "那个小项目先放放。" },
    ],
  },
  "u-an": {
    nodes: [
      { id: "root", parentId: null, name: "我的状态", type: "root" },
      { id: "work", parentId: "root", name: "工作", type: "domain", domain: "work", brief: "视觉稿已经交出去了。" },
      {
        id: "work-ui",
        parentId: "work",
        name: "设置页改版",
        type: "project",
        domain: "work",
        progress: 0.9,
        status: "flowing",
        brief: "等研发过一遍，不用再画了。",
        estimateMin: 15,
        nextAction: "周四一起看稿时只记问题，当场别改",
        nextHint: "带一页标注说明就够了。",
        updatedAt: "昨天 18:00",
      },
      { id: "study", parentId: "root", name: "学习", type: "domain", domain: "study" },
      {
        id: "study-type",
        parentId: "study",
        name: "字体课作业",
        type: "project",
        domain: "study",
        progress: 0.5,
        status: "active",
        estimateMin: 40,
        nextAction: "把第三张对比稿做完",
        nextHint: "只比字重，别顺手做成海报。",
        updatedAt: "周日",
      },
      { id: "life", parentId: "root", name: "生活", type: "domain", domain: "life" },
      {
        id: "life-walk",
        parentId: "life",
        name: "傍晚散步",
        type: "project",
        domain: "life",
        progress: 0.8,
        status: "flowing",
        nextAction: "今天照样走 30 分钟",
        nextHint: "不用打卡，出门走走就算。",
        updatedAt: "今天",
      },
      { id: "proj", parentId: "root", name: "项目", type: "domain", domain: "proj" },
    ],
  },
  "u-zhou": {
    nodes: [
      { id: "root", parentId: null, name: "我的状态", type: "root" },
      { id: "work", parentId: "root", name: "工作", type: "domain", domain: "work", brief: "助教那边的事都做完了。" },
      { id: "study", parentId: "root", name: "学习", type: "domain", domain: "study", brief: "现在只有开题这一件事。" },
      {
        id: "study-prop",
        parentId: "study",
        name: "开题报告",
        type: "project",
        domain: "study",
        progress: 0.62,
        status: "waiting",
        brief: "初稿交了，等老师批注。",
        blockedReason: "老师这周出差，估计周五前不会回。",
        estimateMin: 10,
        nextAction: "写封短信问一下，周五方不方便给意见",
        nextHint: "三句话就够，别再附一版新的。",
        updatedAt: "周一",
      },
      {
        id: "study-lit",
        parentId: "study-prop",
        name: "文献表",
        type: "task",
        domain: "study",
        progress: 0.8,
        status: "active",
        estimateMin: 30,
        nextAction: "再补 3 篇 2024 年以后的论文",
        nextHint: "只记问题和做法，别写长摘录。",
        updatedAt: "昨天",
      },
      { id: "life", parentId: "root", name: "生活", type: "domain", domain: "life" },
      {
        id: "life-home",
        parentId: "life",
        name: "宿舍琐事",
        type: "project",
        domain: "life",
        progress: 0.3,
        status: "active",
        estimateMin: 15,
        nextAction: "约一下洗衣机",
        nextHint: "今晚 8 点前搞定。",
        updatedAt: "今天",
      },
      { id: "proj", parentId: "root", name: "项目", type: "domain", domain: "proj" },
    ],
  },
};
